
image:
  repository: positionpal/gateway
  tag: 3.0.0@sha256:364808e0d5f5b5a1f94b5dd7b127e12b14131ffbe00dd0005e5ce4ee5f0a1d8a
  pullPolicy: IfNotPresent

serviceName: gateway-service
replicaNumber: 1

outputPort: 3000

locationServiceHttpUrl: http://locservice:8080
locationApiVersion: v1
locationServiceGrpcUrl: locservice:5052
chatServiceHttpUrl: http://chatservice:8080
chatApiVersion: v1
chatServiceGrpcUrl: chatservice:5052
userServiceGrpcUrl: ""
notificationServiceGrpcUrl: notificationservice:5052
