config:
  image:
    repository: positionpal/gateway
    tag: 2.5.7@sha256:b4d11784dcc4b70199b739b1411613e98c7ecc27bf7eeab92c0a870b3f3ad7ab
    pullPolicy: IfNotPresent

  servicename: gateway-service
  replicaNumber: 1

  outputPort: 3000

  locationServiceHttpUrl: http://locservice:8080
  locationApiVersion: v1
  locationServiceGrpcUrl: locservice:5052
  chatServiceHttpUrl: http://chatservice:8080
  chatApiVersion: v1
  chatServiceGrpcUrl: chatservice:5052
  userServiceGrpcUrl: pp-us-user-service.user-service:5052
  notificationServiceGrpcUrl: notificationservice:5052
