config:
  image:
    repository: positionpal/gateway
    tag: 2.5.2@sha256:1c45a572c293fa899dbbe3d27483239082a8af4530d158daf3059af575a3de96
    pullPolicy: IfNotPresent

  servicename: gateway-service
  replicaNumber: 1

  outputPort: 3000

  locationServiceHttpUrl: http://locservice:8080
  locationApiVersion: v1
  locationServiceGrpcUrl: locservice:5052
  chatServiceHttpUrl: http://chatservice:8080
  chatApiVersion: v1
  chatServiceGrpcUrl: chatservice:5052
  userServiceGrpcUrl: pp-us-user-service.user-service:5052
  notificationServiceGrpcUrl: notificationservice:5052
