apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "gateway-service.labels" . | nindent 4 }}
  name: {{ .Values.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaNumber }}
  selector:
    matchLabels:
      {{- include "gateway-service.labels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "gateway-service.labels" . | nindent 8 }}
    spec:
      containers:
        {{- include "gateway-service.container" . | nindent 8 }}