apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.servicename }}
  namespace: {{ .Release.Namespace }}
  labels:
   {{- include "gateway-service.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ .Values.config.servicename }}
  ports:
    - protocol: TCP
      port: {{ .Values.config.outputPort }}
      targetPort: {{ .Values.config.outputPort }}
      name: http
  type: ClusterIP