apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-gateway-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gateway-service.labels" . | nindent 4 }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.config.outputPort }}
      targetPort: {{ .Values.config.outputPort }}
      name: http
  type: ClusterIP
  selector:
  {{- include "gateway-service.labels" . | nindent  4}}